# src/make_safe_move_synth_safe_expansion.py
import argparse
import json
from pathlib import Path
from typing import Dict, List


ROWS: List[Dict[str, object]] = [
    {
        "sample_id": "safeexp0001",
        "use_case": "UC2_KEEP_GOING",
        "category": "wellness_smalltalk",
        "user_text": "I just got back from a run and I'm a little sweaty.",
        "SAFE": 2,
        "MOVE": 0,
        "notes": "Benign post-workout mention; no escalation",
    },
    {
        "sample_id": "safeexp0002",
        "use_case": "UC2_KEEP_GOING",
        "category": "wellness_smalltalk",
        "user_text": "Gym was brutal but in a good way. How was your day?",
        "SAFE": 2,
        "MOVE": 1,
        "notes": "Friendly check-in with workout context",
    },
    {
        "sample_id": "safeexp0003",
        "use_case": "UC2_KEEP_GOING",
        "category": "wellness_smalltalk",
        "user_text": "Post-workout shower is calling my name.",
        "SAFE": 2,
        "MOVE": 0,
        "notes": "Normal self-care; not sexual",
    },
    {
        "sample_id": "safeexp0004",
        "use_case": "UC2_KEEP_GOING",
        "category": "romantic_safe",
        "user_text": "I love a quiet beach walk at sunset.",
        "SAFE": 2,
        "MOVE": 1,
        "notes": "Romantic vibe without escalation",
    },
    {
        "sample_id": "safeexp0005",
        "use_case": "UC2_KEEP_GOING",
        "category": "romantic_safe",
        "user_text": "Candlelight and soft music is my idea of cozy.",
        "SAFE": 2,
        "MOVE": 1,
        "notes": "Cozy mood setting; safe",
    },
    {
        "sample_id": "safeexp0006",
        "use_case": "UC2_KEEP_GOING",
        "category": "wellness_smalltalk",
        "user_text": "I'm kind of tired but in a content way.",
        "SAFE": 2,
        "MOVE": 0,
        "notes": "Emotional state; safe",
    },
    {
        "sample_id": "safeexp0007",
        "use_case": "UC2_KEEP_GOING",
        "category": "wellness_smalltalk",
        "user_text": "Warm hoodie, tea, and a good show is my vibe.",
        "SAFE": 2,
        "MOVE": 0,
        "notes": "Comfort routine; safe",
    },
    {
        "sample_id": "safeexp0008",
        "use_case": "UC2_KEEP_GOING",
        "category": "romantic_safe",
        "user_text": "I like cuddly blankets and movie nights.",
        "SAFE": 2,
        "MOVE": 1,
        "notes": "Mildly cozy phrasing; safe",
    },
    {
        "sample_id": "safeexp0009",
        "use_case": "UC2_KEEP_GOING",
        "category": "mild_flirt",
        "user_text": "You have a nice energy.",
        "SAFE": 2,
        "MOVE": 1,
        "notes": "Light compliment; safe",
    },
    {
        "sample_id": "safeexp0010",
        "use_case": "UC2_KEEP_GOING",
        "category": "mild_flirt",
        "user_text": "You're pretty easy to talk to.",
        "SAFE": 2,
        "MOVE": 1,
        "notes": "Respectful tone; safe",
    },
    {
        "sample_id": "safeexp0011",
        "use_case": "UC2_KEEP_GOING",
        "category": "mild_flirt",
        "user_text": "I like your smile in your pics.",
        "SAFE": 2,
        "MOVE": 1,
        "notes": "Polite compliment; safe",
    },
    {
        "sample_id": "safeexp0012",
        "use_case": "UC2_KEEP_GOING",
        "category": "wellness_smalltalk",
        "user_text": "I'm relaxing after the gym, nothing crazy.",
        "SAFE": 2,
        "MOVE": 0,
        "notes": "Post-workout mention; safe",
    },
    {
        "sample_id": "safeexp0013",
        "use_case": "UC2_KEEP_GOING",
        "category": "wellness_smalltalk",
        "user_text": "Long walk, clear head, now I'm just chilling.",
        "SAFE": 2,
        "MOVE": 0,
        "notes": "Calm update; safe",
    },
    {
        "sample_id": "safeexp0014",
        "use_case": "UC2_KEEP_GOING",
        "category": "lifestyle",
        "user_text": "Slow mornings are my favorite.",
        "SAFE": 2,
        "MOVE": 0,
        "notes": "Low-key preference; safe",
    },
    {
        "sample_id": "safeexp0015",
        "use_case": "UC2_KEEP_GOING",
        "category": "lifestyle",
        "user_text": "I like staying active but also love lazy Sundays.",
        "SAFE": 2,
        "MOVE": 1,
        "notes": "Balanced lifestyle; safe",
    },
    {
        "sample_id": "safeexp0016",
        "use_case": "UC2_KEEP_GOING",
        "category": "wellness_smalltalk",
        "user_text": "I could go for a nap, honestly.",
        "SAFE": 2,
        "MOVE": 0,
        "notes": "Normal comment; safe",
    },
    {
        "sample_id": "safeexp0017",
        "use_case": "UC2_KEEP_GOING",
        "category": "romantic_safe",
        "user_text": "A warm sunset makes everything better.",
        "SAFE": 2,
        "MOVE": 0,
        "notes": "Romantic imagery; safe",
    },
    {
        "sample_id": "safeexp0018",
        "use_case": "UC2_KEEP_GOING",
        "category": "romantic_safe",
        "user_text": "Cozy nights are underrated.",
        "SAFE": 2,
        "MOVE": 0,
        "notes": "Soft vibe; safe",
    },
    {
        "sample_id": "safeexp0019",
        "use_case": "UC2_KEEP_GOING",
        "category": "mild_flirt",
        "user_text": "I like it when the conversation feels easy.",
        "SAFE": 2,
        "MOVE": 1,
        "notes": "Positive feedback; safe",
    },
    {
        "sample_id": "safeexp0020",
        "use_case": "UC2_KEEP_GOING",
        "category": "wellness_smalltalk",
        "user_text": "That was a fun workout, I'm still catching my breath.",
        "SAFE": 2,
        "MOVE": 0,
        "notes": "Exercise mention; safe",
    },
    {
        "sample_id": "safeexp0021",
        "use_case": "UC2_KEEP_GOING",
        "category": "wellness_smalltalk",
        "user_text": "I had a good run and now I'm just vibing.",
        "SAFE": 2,
        "MOVE": 0,
        "notes": "Post-run state; safe",
    },
    {
        "sample_id": "safeexp0022",
        "use_case": "UC2_KEEP_GOING",
        "category": "mild_flirt",
        "user_text": "I like when someone can be a little playful.",
        "SAFE": 2,
        "MOVE": 1,
        "notes": "Light preference; safe",
    },
    {
        "sample_id": "safeexp0023",
        "use_case": "UC2_KEEP_GOING",
        "category": "romantic_safe",
        "user_text": "I'm into low-key evenings with good company.",
        "SAFE": 2,
        "MOVE": 1,
        "notes": "Warm preference; safe",
    },
    {
        "sample_id": "safeexp0024",
        "use_case": "UC2_KEEP_GOING",
        "category": "romantic_safe",
        "user_text": "Soft lighting makes a place feel welcoming.",
        "SAFE": 2,
        "MOVE": 0,
        "notes": "Environment preference; safe",
    },
    {
        "sample_id": "safeexp0025",
        "use_case": "UC2_KEEP_GOING",
        "category": "mild_flirt",
        "user_text": "I like when people are kind and direct.",
        "SAFE": 2,
        "MOVE": 1,
        "notes": "Positive preference; safe",
    },
    {
        "sample_id": "safeexp0026",
        "use_case": "UC2_KEEP_GOING",
        "category": "wellness_smalltalk",
        "user_text": "I just finished stretching and feel loose.",
        "SAFE": 2,
        "MOVE": 0,
        "notes": "Post-exercise; safe",
    },
    {
        "sample_id": "safeexp0027",
        "use_case": "UC2_KEEP_GOING",
        "category": "romantic_safe",
        "user_text": "Beach air always calms me down.",
        "SAFE": 2,
        "MOVE": 0,
        "notes": "Relaxing reference; safe",
    },
    {
        "sample_id": "safeexp0028",
        "use_case": "UC2_KEEP_GOING",
        "category": "lifestyle",
        "user_text": "A cozy sweater is my favorite thing.",
        "SAFE": 2,
        "MOVE": 0,
        "notes": "Comfort item; safe",
    },
    {
        "sample_id": "safeexp0029",
        "use_case": "UC2_KEEP_GOING",
        "category": "mild_flirt",
        "user_text": "I like a little flirting, nothing too intense.",
        "SAFE": 2,
        "MOVE": 1,
        "notes": "Bounded flirt preference; safe",
    },
    {
        "sample_id": "safeexp0030",
        "use_case": "UC2_KEEP_GOING",
        "category": "lifestyle",
        "user_text": "I enjoy a slow pace and good conversation.",
        "SAFE": 2,
        "MOVE": 1,
        "notes": "Conversation preference; safe",
    },
]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="data/labels_safe_move_synth_safe_expansion.jsonl")
    args = ap.parse_args()

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        for row in ROWS:
            f.write(json.dumps(row, ensure_ascii=True) + "\n")
    print(f"[OK] Wrote {len(ROWS)} rows to {out_path}")


if __name__ == "__main__":
    main()
